package dam.hbnt.projectemployees.programa.model;
// Generated 6 de febr. 2020, 10:16:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departments generated by hbm2java
 */
public class Departments  implements java.io.Serializable {


     private String deptNo;
     private String deptName;
     private Set deptEmps = new HashSet(0);

    public Departments() {
    }

	
    public Departments(String deptNo, String deptName) {
        this.deptNo = deptNo;
        this.deptName = deptName;
    }
    public Departments(String deptNo, String deptName, Set deptEmps) {
       this.deptNo = deptNo;
       this.deptName = deptName;
       this.deptEmps = deptEmps;
    }
   
    public String getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
    public Set getDeptEmps() {
        return this.deptEmps;
    }
    
    public void setDeptEmps(Set deptEmps) {
        this.deptEmps = deptEmps;
    }

    @Override
    public String toString() {
        return "ID: "+ deptNo+ " Name: "+ deptName;
    }




}


