package dam.hbnt.projectemployees.model;
// Generated 5 de febr. 2020, 13:17:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private int empNo;
     private Date birthDate;
     private String firstName;
     private String lastName;
     private char gender;
     private Date hireDate;

    public Employees() {
    }

    public Employees(int empNo, Date birthDate, String firstName, String lastName, char gender, Date hireDate) {
       this.empNo = empNo;
       this.birthDate = birthDate;
       this.firstName = firstName;
       this.lastName = lastName;
       this.gender = gender;
       this.hireDate = hireDate;
    }
   
    public int getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(int empNo) {
        this.empNo = empNo;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public char getGender() {
        return this.gender;
    }
    
    public void setGender(char gender) {
        this.gender = gender;
    }
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }




}


